################################################################################################################################
#
# ███████╗░█████╗░██╗░░░██╗░█████╗░████████╗██╗░█████╗░███╗░░██╗██╗░░██╗░█████╗░██╗░░░██╗░██████╗███████╗██╗░░░██╗░░██╗██╗
# ╚════██║██╔══██╗██║░░░██║██╔══██╗╚══██╔══╝██║██╔══██╗████╗░██║██║░░██║██╔══██╗██║░░░██║██╔════╝██╔════╝██║░░░██║░██╔╝██║
# ░░███╔═╝███████║██║░░░██║██║░░╚═╝░░░██║░░░██║██║░░██║██╔██╗██║███████║██║░░██║██║░░░██║╚█████╗░█████╗░░╚██╗░██╔╝██╔╝░██║
# ██╔══╝░░██╔══██║██║░░░██║██║░░██╗░░░██║░░░██║██║░░██║██║╚████║██╔══██║██║░░██║██║░░░██║░╚═══██╗██╔══╝░░░╚████╔╝░███████║
# ███████╗██║░░██║╚██████╔╝╚█████╔╝░░░██║░░░██║╚█████╔╝██║░╚███║██║░░██║╚█████╔╝╚██████╔╝██████╔╝███████╗░░╚██╔╝░░╚════██║
# ╚══════╝╚═╝░░╚═╝░╚═════╝░░╚════╝░░░░╚═╝░░░╚═╝░╚════╝░╚═╝░░╚══╝╚═╝░░╚═╝░╚════╝░░╚═════╝░╚═════╝░╚══════╝░░░╚═╝░░░░░░░░╚═╝
#
#   Sponsor: https://minestrator.com/a/FAIRYSKY
#   Documentation: https://zauctionhouse.groupez.dev/
#   Discord: https://discord.groupez.dev/
#
################################################################################################################################

date-format: dd/MM/yyyy HH:mm:ss
# Enables detailed logs and error messages in the console.
# If you need support, make sure to activate this option and check your console logs.
enable-debug: false

#
# - SQLITE
# - MARIADB
# - MYSQL
storage-type: SQLITE

# Database configuration.
# It is strongly recommended to use a database to store all plugin data.
database-configuration: # Prefix applied to all tables created by the plugin.
  # If you use the same database for multiple plugins, this helps avoid conflicts.
  # It is recommended not to change this value once the plugin is in use.
  table-prefix: zauctionhouse_
  # IP address of the machine hosting your database.
  host: 192.168.10.10
  # Port of your database server.
  # Default MySQL port: 3306
  port: 3306
  # Username used to log into the database.
  user: homestead
  # Password associated with the database user.
  password: secret
  # Name of the database where data will be stored.
  database: zauctionhouse
  # Enables SQL debugging.
  # Activates verbose SQL logs, useful for identifying database issues.
  debug: true

# Vous permet de définir des clés qui seront remplacées par la couleur pour vos messages.
# Cela permet de simplifier la configuration de vos messages
message-colors:
  - key: <primary>
    color: '#24d65d'
  - key: <secondary>
    color: '#656665'
  - key: <error>
    color: '#ff0000'
  - key: <success>
    color: '#00ff00'

# Configuration des commandes, aliases, arguments
# Pour reload cette configuration, vous devez relancer votre serveur !
commands: # Commande principale, /zauctionhouse
  main-command: # Aliases de la commande principale
    aliases:
      - ah
      - hdv
      - auction
      - zauction
  
  # Commande de vente /zauctionhouse sell
  sell:
    aliases:
      - sell
      - s
      - vendre
    arguments:
      - name: price
        display-name: price
        required: true
        auto-completion:
          - 1000
          - 10000
          - 25000
      - name: amount
        display-name: amount
        required: false
        auto-completion:
          - '1'
          - '%max-stack-size%'
      - name: economy
        display-name: economy
        required: false
        auto-completion:
          - vault

number-sell-multiplication:
  enable: true
  formats:
    - format: K
      multiplication: 1000
    - format: M
      multiplication: 1000000
    - format: B
      multiplication: 1000000000
    - format: T
      multiplication: 1000000000000
    - format: Q
      multiplication: 1000000000000000
    - format: QQ
      multiplication: 1000000000000000000
    - format: S
      multiplication: 1000000000000000000000
    - format: SS
      multiplication: 1000000000000000000000000
    - format: O
      multiplication: 1000000000000000000000000000
    - format: N
      multiplication: 1000000000000000000000000000000
    - format: D
      multiplication: 1000000000000000000000000000000000
    - format: UN
      multiplication: 1000000000000000000000000000000000000
    - format: DD
      multiplication: 1000000000000000000000000000000000000000
    - format: TR
      multiplication: 1000000000000000000000000000000000000000000

expiration:
  sell: # Le default permission doit être la valeur la plus petite
    default-expiration: 172800
    permission:
      enable: false
      permissions:
        - permission: zauctionhouse.expiration.vip
          expiration: 3600
        - permission: zauctionhouse.expiration.elite
          expiration: 7200
        - permission: zauctionhouse.expiration.legend
          expiration: 259200
  
  bid:
    default-expiration: 172800
    permission:
      enable: false
      permissions:
        - permission: zauctionhouse.expiration.vip
          expiration: 3600
        - permission: zauctionhouse.expiration.elite
          expiration: 7200
        - permission: zauctionhouse.expiration.legend
          expiration: 259200
  
  rent:
    default-expiration: 172800
    permission:
      enable: false
      permissions:
        - permission: zauctionhouse.expiration.vip
          expiration: 3600
        - permission: zauctionhouse.expiration.elite
          expiration: 7200
        - permission: zauctionhouse.expiration.legend
          expiration: 259200
  
  expire:
    default-expiration: 604800
    permission:
      enable: false
  
  purchase:
    default-expiration: 604800
    permission:
      enable: false

item-lore:
  listed-auction-item:
    - ""
    - "<white>⌂ #92ffffSeller#8c8c8c: #2CCED2%seller%"
    - "<white>☆ #92ffffPrice#8c8c8c: #2CCED2%price%"
    - "<white>⌚ #92ffffExpire#8c8c8c: #969696%time-remaining%"
    - ""
    - "%status%"

  expired-item:
    - ""
    - "<white>⌚ #92ffffExpire#8c8c8c: #969696%time-remaining%"
    - ""
    - "#8c8c8c• #2CCED2Click to retrieve this item"

  purchased-item:
    - ""
    - "<white>⌚ #92ffffExpire#8c8c8c: #969696%time-remaining%"
    - ""
    - "#8c8c8c• #2CCED2Click to retrieve this item"

  owned-item:
    - ""
    - "<white>⌚ #92ffffExpire#8c8c8c: #969696%time-remaining%"
    - ""
    - "#8c8c8c• #2CCED2Click to retrieve this item"

  status:
    seller: "#8c8c8c• #2CCED2ᴄʟɪᴄᴋ #92ffffᴛᴏ ʀᴇᴛʀɪᴇᴠᴇ ᴛʜɪs ɪᴛᴇᴍ"
    buyer: "#8c8c8c• #2CCED2ᴄʟɪᴄᴋ #92ffffᴛᴏ ʙᴜʏ ᴛʜɪs ɪᴛᴇᴍ"


time: # ---- Unités (singulier / pluriel) ----
  second: second
  seconds: seconds
  
  minute: minute
  minutes: minutes
  
  hour: hour
  hours: hours
  
  day: day
  days: days

  # ---- Formats de temps ----
  # %02d = valeur numérique (jours / heures / minutes / secondes)
  # %second%, %minute%, %hour%, %day% = unité adaptée en fonction du quantificateur
  # Exemple : "1 day", "2 days", "01ᴅ 02ʜ 30ᴍ", etc.

  # Format utilisé pour les durées >= 1 jour
  time-day: '%02dᴅ %02dʜ %02dᴍ'
  
  # Format utilisé pour les durées >= 1 heure, mais < 1 jour
  time-hour: '%02dʜ %02dᴍ %02ds'
  
  # Format utilisé pour les durées >= 1 minute, mais < 1 heure
  time-minute: '%02dᴍ %02ds'
  
  # Format utilisé pour les durées < 1 minute
  time-second: '%02ds'

action:
  
  remove-listed-item: # On donne l'item après avoir retiré l'item de la vente
    give-item: false
    
    # On ouvre l'inventaire après l'avoir retiré
    open-inventory: true

    # Permet d'ouvrir l'inventaire de confirmation
    open-confirm-inventory: true
  
  remove-expired-item:
    
    # On ouvre l'inventaire après l'avoir retiré
    open-inventory: true
  
  purchased-item:

    # On donne l'item après l'achat
    give-item: false

    # Si l'option give item est active, alors cette option va vérifier le contenu de l'inventaire du joueur et vérifier s'il a assez de place pour recevoir le ou les objets.
    player-inventory-must-have-free-space: true

    # On ouvre l'inventaire après l'avoir retiré de l'inventaire des items acheté
    open-inventory: true

    # On affiche un item d'erreur
    money-item:
      enable: true # Activé / désactivé
      duration: 60 # Durée en ticks
      item: # Item à afficher
        material: BARRIER
        name: "#ff3535✘ You don't have enough money to buy this!"

    # Envoie un message si le joueur n'a pas assez d'argent
    money-message: true

  owned-item:

    # On ouvre l'inventaire après l'avoir retiré de l'inventaire de mes items
    open-inventory: true

# Système de tri
sort-items:

  # Tri par défaut
  default-sort: DECREASING_DATE

  translations:
    ASCENDING_PRICE: "ᴀsᴄᴇɴᴅɪɴɢ ᴘʀɪᴄᴇ"
    ASCENDING_DATE: "ᴀsᴄᴇɴᴅɪɴɢ ᴅᴀᴛᴇ"
    DECREASING_DATE: "ᴅᴇᴄʀᴇᴀsɪɴɢ ᴅᴀᴛᴇ"
    DECREASING_PRICE: "ᴅᴇᴄʀᴇᴀsɪɴɢ ᴘʀɪᴄᴇ"

